#!/usr/bin/python3
# PSDX-FileCopyrightText: 2024 Soshi Saiki
# SPDX-License-Identifier: BSD-3-Clause

try:
    a =  float(input("最初の数字を入力: "))
except ValueError:
    print("エラー: 数字を入力してください")
    exit(1)

while True:
    try:
        s, b = input("符号(+,m,*,/)と半角スペース後に数字を入力: ").split()
        b = float(b)
    except ValueError:
        print("エラー: 正しい形式で入力してください")
        continue

    if s == '+':
        c = a + b
    elif s == 'm':
        c = a - b
    elif s == '*':
        c = a * b
    elif s == '/':
        if b != 0:
            c = a / b
        else:
            print("エラー: 0で割ることはできません")
            continue
    else:
        print("エラー: 無効な符号です")
        continue

    print(f"計算結果: {c}")
    a = c
